spring:
  datasource:
    url: url of ur db
    username: username of ur db
    password: password of ur db

jwt:
  secret: your-jwt-secret-key
  expiration: 3600000


razorpay:
  key-id: id-daaldo
  key-secret: secret-key here
